### PR TITLE
Add React 16 as peer dependency

### LINKED ISSUE #19: Add React 16 as peer dependencie
Please add React 16 as peer dependencie. Everything seems to be working fine.

### PR DESCRIPTION
**Pull request by nanexcool**
Fixes #19

### CODE REVIEW

**Comment by Archinowsk** [comment]
@ameyms Any schedule for accepting this and releasing a new version?

**Comment by ameyms** [comment]
Ah. Sorry about that. I will do it today.

**Comment by ameyms** [comment]
Just a quick update that I am experiencing issues while making releases with npm 5. 
👉  See npm/npm#16723, npm/npm#18408.

I am working on it.

**Comment by ameyms** [comment]
Done. Sorry once again for the delay. The latest version `0.4.4` is now available on npm. https://www.npmjs.com/package/react-animated-number

**Comment by Archinowsk** [comment]
Awesome, thank you!

**Pull request merged**
